import = [ "~/.config/alacritty/themes/2c-default.toml" ]

[bell]
	duration = 0

[colors]
	draw_bold_text_with_bright_colors = true

[cursor]
	blink_interval = 800
	thickness = 0.15
	unfocused_hollow = false

	[cursor.style]
		blinking = "On"
		shape = "Beam"

[font]
	# Font size. Values for different font options:
	#   "EnvyCodeR":14,
	#   "ProggyClean CE Nerd Font":18
	#   "AnonymicePro Nerd Font":15
	#   "Hurmit Nerd Font":12
	size = 14

	[font.bold]
		family = "EnvyCodeR Nerd Font"
		style = "Bold"

	[font.bold_italic]
		family = "EnvyCodeR Nerd Font"
		style = "Bold Italic"

	[font.italic]
		family = "EnvyCodeR Nerd Font"
		style = "Italic"

	[font.normal]
		family = "EnvyCodeR Nerd Font"
		style = "Regular"

	[font.offset]
		# EnvyCodeR Nerd Font: -1 -1
		x = -1
		y = -1

[scrolling]
	history = 5000
	multiplier = 8

[selection]
	save_to_clipboard = false

[window]
	dynamic_padding = true
	opacity = 0.85

	[window.padding]
		x = 12
		y = 8
